src/Entity/Advert.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\AdvertRepository")
 */
class Advert
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="advert")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="datetime")
     */
    private $updated_at;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $description;

    public function __construct() {
        $this->created_at = new \DateTime('now');
        $this->updated_at = new \DateTime('now');

    }

    public function getId()
    {
        return $this->id;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUserId(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    /**
     * Trim description text for display purposes
     *
     * @param $start
     * @param $end
     * @return string
     */
    public function trimDescription($start, $end)
    {
        $description =  $this->getDescription();

        if($description !== null || $description !== '') {

            if(strlen($description) > $end) {
                return substr($description, $start, $end) . '...';
            }

            return $description;
        }

        return '';
    }

    /**
     * Wrap description text for display purposes
     *
     * @param $length
     * @return string
     */
    public function wrapDescription($length)
    {
        $description =  $this->getDescription();

        if($description !== null || $description !== '') {
            return wordwrap($description, $length, "<br />\n", true);
        }

        return '';
    }
}

src/Controller/AdvertBoard/HomePageController.php
<?php

namespace App\Controller\AdvertBoard;

use App\Entity\Advert;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;

class HomePageController extends AbstractController
{

    /**
     * @Route("/", name="homepage")
     */
    public function homepage()
    {

        $doctrine = $this->getDoctrine();
        $adverts = $doctrine->getRepository(Advert::class)->findAdvertsWithUser();

        return $this->render('homepage/index.html.twig', [
            'adverts' => $adverts
        ]);
    }

}

templates/homepage/index.html.twig
{% extends "base.html.twig" %}

{% block body %}

    <div class="row mt-4">
        <div class="col align-self-end">
            <h1 class="h1">Current Adverts</h1>
        </div>
        {% if is_granted('IS_AUTHENTICATED_FULLY') %}
            <div class="col-sm-2">
                <a type="button" class="btn btn-success new-advert" role="button" href="{{ path('advert_create') }}">Create new</a>
            </div>
        {% endif %}
    </div>

    <div class="row">
        {% for key, advert in adverts %}
            <div class="col-sm-4 advert-space shadow p-3 mb-5 bg-white rounded">
                <h2> Advert #{{ advert.id }} </h2> {# temporary counter by id #}
                <ul style="list-style-type: none;">
                    <li><b>Username:</b> {{ advert.user.username }}</li>
                    <li><b>Advert name:</b> {{ advert.name }}</li>
                    <li><b>Description:</b> {{ advert.wrapDescription(30)|striptags }}</li>
                    <li><b>Created At:</b> {{ advert.createdAt|date }}</li>
                </ul>
            </div>
        {% endfor %}
    </div>

{% endblock %}